### ISSUE TITLE
生成的dll通达信加载不了

### ISSUE THREAD

**Issue by zghnx** [figozhu/tdx_macd_area#2]
生成的dll通达信加载不了

**Comment by figozhu** [comment]
> 生成的dll通达信加载不了

好像最新版的通达信不支持dll了？确认一下使用的通达信的版本。
另外计算MACD面积，可以不用dll了，用通达信内置的语法也可以实现了。

**Comment by zghnx** [comment]
> 

可以了，支持32位。64位导入不了。原意是读出外部数据如mysql,redis等

**Comment by zghnx** [comment]
> > 生成的dll通达信加载不了
> 
> 好像最新版的通达信不支持dll了？确认一下使用的通达信的版本。 另外计算MACD面积，可以不用dll了，用通达信内置的语法也可以实现了。

个有疑问；
// 函数(数据个数,输出,输入a,输入b,输入c)
typedef void(*pPluginFUNC)(int,float*,float*,float*,float*);

调用时:AREA:=TDXDLL1(1, MACD, 0, 0); 参数对不上。怎么可以？
